name: Java CI

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Java main method
      run: |
        java -ea -cp target/classes org.example.test.TestFileProceed
